### ISSUE TITLE
Add routes

### ISSUE THREAD

**Issue by chriswhong** [chriswhong/mtaMarylandBusTracking#3]
Add toggleable routes as geojson

**Comment by talllguy** [comment]
Finally something I can help with. I exported some Baltimore bus routes on OSM with [this script on overpass-turbo.edu](http://overpass-turbo.eu/s/7CG) and then pop'd that geoJSON in a gist to see if it would render OK. Here's [a 2MB test](https://gist.github.com/talllguy/8f69f04a76f6f3155f18) covering just routes that cross downtown. Looks like the attributes aren't there but it is a potential source for this kind of data.

**Comment by chriswhong** [comment]
A shape file for all routes is on the Maryland esri portal... just need to
add it and style.  Do you know how to do that with leaflet?

**Comment by talllguy** [comment]
Oh, even better to get the shapefile. I don't know how to stylize in leaflet though :frowning: ... I could learn

**Comment by chriswhong** [comment]
Learn!  You want to use L.geojson, here's an example:
http://leafletjs.com/examples/geojson.html

Hit me up on gchat if you want some pointers.

**Comment by talllguy** [comment]
@chriswhong fixed in 5f13b3344fd7b49d78fbd40f9cb6ed85ca60417a
